package com.ising99.intelligentremotecontrol.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "DEVICE_ENTITY".
 */
@Entity
public class DeviceEntity {

    @Id
    private String address;

    @NotNull
    private String name;
    private String settings;

    @NotNull
    private java.util.Date update_at;

    @NotNull
    private java.util.Date create_at;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public DeviceEntity() {
    }

    public DeviceEntity(String address) {
        this.address = address;
    }

    @Generated
    public DeviceEntity(String address, String name, String settings, java.util.Date update_at, java.util.Date create_at) {
        this.address = address;
        this.name = name;
        this.settings = settings;
        this.update_at = update_at;
        this.create_at = create_at;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @NotNull
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(@NotNull String name) {
        this.name = name;
    }

    public String getSettings() {
        return settings;
    }

    public void setSettings(String settings) {
        this.settings = settings;
    }

    @NotNull
    public java.util.Date getUpdate_at() {
        return update_at;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUpdate_at(@NotNull java.util.Date update_at) {
        this.update_at = update_at;
    }

    @NotNull
    public java.util.Date getCreate_at() {
        return create_at;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreate_at(@NotNull java.util.Date create_at) {
        this.create_at = create_at;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
